### ISSUE TITLE
Why are there two license files (LICENSE & COPYING)?

### ISSUE THREAD

**Issue by 0mp** [babluboy/bookworm#239] opened 2019-02-21 14:49 UTC
I'm attempting to package bookworm for FreeBSD and I wonder why we've got those two license files in the repository.

**Comment by babluboy** [comment] 2019-02-21 16:35
@0mp Thanks for contributing to Bookworm. The LICENSE file is what I started with, but when the dev standards were defined for Elementary OS the file was named COPYING.

I will delete the LICENSE file from the repo as it’s not required and is a duplicate of the COPYING file

When you are able to package Bookworm for Debian, do let me know the repository location and installation process so that I can mention it on the Bookworm website:
https://babluboy.github.io/bookworm/

**Closed** 2019-03-10 08:51 UTC
Labels: Bug
