### ISSUE TITLE
Multi File picker cant use keyboard keys

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#23] opened 2017-02-27 06:57 UTC
During uploading on Google Drive, I can select files using arrow keys and they look like this in the file chooser.
![screenshot from 2017-02-27 12 53 33](https://cloud.githubusercontent.com/assets/1283240/23351501/ce0b8b6a-fceb-11e6-8113-359d6ef432f8.jpeg)
Bookworm currently can't select by arrow key while importing books to the library. Besides, whenever I try to use the arrow key, the picker gets slow and also unable to use mouse at the moment.

**Comment by babluboy** [comment] 2017-02-27 09:15
This is a strange one. In my case, I see that when the file picker is opened the top file is selected and holding down the shift key I can press the down key to select multiple files consecutively. Similarly, using the mouse and the shift key I can select multiple files. Also there is no lag when selecting by keyboard and mouse. Since I'm using the default FilePicker, the system behavior should be the same. Will try on my VM and see if I can see any issue.
![fileselect](https://cloud.githubusercontent.com/assets/14061478/23355360/3ada3af8-fccd-11e6-9aa2-cf3365ee73e4.jpeg)

**Comment by babluboy** [comment] 2017-06-16 22:23
Closing this issue as I'm not able to reproduce it...please reopen if you are still seeing this in the latest release of bookworm in appcenter - v0.7

**Closed by babluboy** 2017-06-16 22:23 UTC
Labels: Triage
